### ISSUE TITLE
Plugin error when using Firefox with Travis

### ISSUE THREAD

**Issue by gziolo** [princed/karma-chai-plugins#10]
I got following error when using plugin with Travis. It works perfectly fine on my local machine. Karma conf setup:
https://github.com/gziolo/game-of-life/blob/76583c5621259a31a44f1e5ea3f31ed12199656d/karma.conf.js

I'm using karma-chai-plugins "~0.2.1" in my package.json

```
Running "karma:continuous" (karma) task
INFO [karma]: Karma v0.12.9 server started at http://localhost:9876/
INFO [launcher]: Starting browser Firefox
INFO [Firefox 19.0.0 (Linux)]: Connected on socket C7K4bYHupB63LoMeRq79 with id 65298600
Firefox 19.0.0 (Linux) ERROR: 'There is no timestamp for /absolute/home/travis/build/gziolo/game-of-life/node_modules/karma-chai-plugins/node_modules/chai/chai.js!'
```

Any idea what could go wrong? Temporary I fixed that using bower repo and requirejs setup. Anyway I would like to continue using plugin :)

**Comment by princed** [comment]
Does it reproduce now?
