### ISSUE TITLE
Update sinon-chai to 2.9.0

### ISSUE THREAD

**Issue by jscharett** [princed/karma-chai-plugins#124]
The sinon-chai library has pushed an update to support sinon 2.1.0 as well.  Can karma-chai-plugins be updated to match?

**Comment by princed** [comment]
Current range of sinon-chai (`^2.8.0`) should cover 2.9.0. 
Could you use please reinstall your packages? Or if you're using yarn try to remove lock-file first, as yarn doesn't support proper update of sub-dependencies.

**Comment by jscharett** [comment]
Removing sinon from my dependencies resolved the issue, however our team
prefers to specify the exact version of deps so everyone is running the
same thing.

**Comment by princed** [comment]
> Removing sinon from my dependencies resolved the issue
Well, that's weird =(

> however our prefers to specify the exact version of deps so everyone is running the same thing
Same for us. BTW, yarn does better job at locking versions than npm.

Closing this, but please let me know if I can help somehow.
