### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by hgossler** [princed/karma-chai-plugins#20]
While trying to use the plugin, I noticed that simply adding the desired plugins to the frameworks array as stated in the README.md, e.g.

```
config.set({
  frameworks: ['mocha', 'chai', 'sinon-chai', 'chai-as-promised', 'chai-jquery'],
 // ...
});
```

does not work. I had to additionally add an entry to the plugins array, like so:

```
plugins: [
  'karma-phantomjs-launcher',
  'karma-mocha',
  'karma-chai-plugins',
  //'karma-chai',
  //'karma-sinon',
  'karma-mocha-reporter',
],
// ...
```

Maybe this should also be included in the docs, or was this possibly caused by something else?

**Comment by martinkr** [comment]
I'm using karma version: 0.13.15 and if i want to use chai-as-promised i need to add the plugin array to the config file (with all dependencies!). Automatically loading via the package.json does not work for me (at least for chai-as-promised). Please update the documentation.
