### ISSUE TITLE
Loading chai plugins along requirejs gives mismatch error

### ISSUE THREAD

**Issue by declandewet** [princed/karma-chai-plugins#3]
This only happens if I load `sinon-chai`, `chai-as-promised` or `jquery-chai`:

![image](http://puu.sh/57sPK.png)

**Comment by unional** [comment]
I have created a pull request to fix this.

**Comment by pankajkumar** [comment]
Anyone has ever figured out solution for this? Seems to be very old issue.

**Comment by unional** [comment]
Pull request have been submitted for this issue.

**Comment by alduethadyn** [comment]
+1 on needing a resolution to this. It's an extremely old issue...

**Comment by kirill-konshin** [comment]
+1 https://github.com/kmees/karma-sinon-chai/issues/13

**Comment by princed** [comment]
Should be fixed in 0.5.0, thanks @unional
