### ISSUE TITLE
No timestamp error

### ISSUE THREAD

**Issue by ronaldsuwandi** [princed/karma-chai-plugins#4]
Everytime I run my test I keep getting these errors (karma 0.10.4)

````
ERROR: 'There is no timestamp for /absolute/Users/ronald/ronald-angulartest/node_modules/karma-chai-plugins/node_modules/chai/chai.js!'
ERROR: 'There is no timestamp for /absolute/Users/ronald/ronald-angulartest/node_modules/karma-chai-plugins/node_modules/sinon-chai/lib/sinon-chai.js!'
````

`karma` installed globally while `karma-chai-plugins` installed locally. The tests seem to be running normally though..

**Comment by Neozaru** [comment]
Same error here : Installed karma-chai-plugins@0.2.4 and chai-as-promised@4.1.1 and got not timestamp errors with "chai.js" and "chai-as-promised.js" (both with "/absolute/" prepended to the path)

**Comment by princed** [comment]
Please check v0.5.0

**Comment by tfrydrychewicz** [comment]
Same error with v0.5.0.

**Comment by geraldyeo** [comment]
I have the same error with v0.5.0

**Comment by adambiggs** [comment]
+1

Still getting the same error with v0.7.0.
