### ISSUE TITLE
busted w/ browserify

### ISSUE THREAD

**Issue by boneskull** [princed/karma-chai-plugins#47]
`sinon` doesn't end up in the global context when used with `karma-browserify`.  I tried to hack around it, but no dice.  Not sure what to do about this one... ended up ditching this package and just `require`-ing each `chai`, `sinon` and `sinon-chai` individually.

**Comment by princed** [comment]
Is there some test case? Or anything I can help with?

**Comment by princed** [comment]
Still actual?

**Comment by boneskull** [comment]
I imagine this is still an issue. I'll remind myself to dig up a reproducible case, but it's probably just misconfiguration on my part

**Comment by princed** [comment]
Feel free to re-open if there's some ideas.
