### ISSUE TITLE
Several bugs related to sinon

### ISSUE THREAD

**Issue by Offirmo** [princed/karma-chai-plugins#90]
* In a webpack build
* with package.json
```
"karma-chai-plugins": "^0.7.0",
```
* with karma config plugins [... require('karma-chai-plugins') ...]
* with karma config frameworks [... 'mocha', 'chai', 'sinon', 'sinon-chai']

> Error: No provider for "framework:sinon"! (Resolving: framework:sinon)
>    at error (.../node_modules/di/lib/injector.js:22:12)

Let's add sinon ourselves : `npm i --save-dev sinon`

> Error: No provider for "framework:sinon"! (Resolving: framework:sinon)
>    at error (.../node_modules/di/lib/injector.js:22:12)

Let's add karma-sinon ourselvess : `npm i --save-dev karma-sinon` + add it in karma config

> TypeError: undefined is not an object

Wasn't `karma-chai-plugins` supposed to bundle all the things ?

**Comment by princed** [comment]
You don't have to include `sinon` manually, `sinon-chai` should be exactly enough.

**Comment by Offirmo** [comment]
@princed so we have to `npm i --save-dev sinon-chai` ? Or are you saying `karma-chai-plugins
` should suffice ? (which is not, hence this report)

**Comment by princed** [comment]
No, you haven't.
I meant you shouldn't include in frameworks list in config as well:  `[... 'mocha', 'chai', 'sinon-chai']`
Sorry for me being confusing.

**Comment by Offirmo** [comment]
Ahh ! I'll try...

**Comment by Offirmo** [comment]
Tricky ! I think I got it. In my code, I'm doing `const expect = require('chai').expect` in order to have a typed expect (for typescript reasons).

However, it appear that doing so returns me another, non sinon-enabled instance of "expect" which is not the same as the global one, which is correctly sinon-enabled. Blame the webpack ?

**Comment by princed** [comment]
All that karma plugins stuff doesn't really connect with webpack. 
But I have some idea for you: you could use [`externals`](http://webpack.github.io/docs/configuration.html#externals) option somewhere in your webpack config for tests to be able to “require” them from global, like:
 ```
// webpack-test.config.js
externals: {
    chai: 'var chai'
}

// test.js
import {expect} from 'chai';
```

**Comment by Offirmo** [comment]
Thanks for the help. I ended up not typing sinon :-( Not sure if my coworkers will agree.

Created a PR for warning of what you told me https://github.com/princed/karma-chai-plugins/pull/91

**Comment by princed** [comment]
Sinon is rather good. Didn't `externals` help you?
